---
title: "Resume"
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: false
# uncomment this line to produce HTML and PDF in RStudio:
knit: pagedown::chrome_print
params:
  cv_name: "Javier Elio"
  data_path: "cv_data.xlsx"
  summary: TRUE
  software: TRUE
  languages: TRUE
  education: TRUE
  employment: TRUE
  teaching: TRUE
  publications: TRUE
  packages: TRUE
  apps: TRUE
  
---

```{r, setup, include=FALSE}

knitr::opts_chunk$set(
  results = 'asis', 
  echo = FALSE,
  message = FALSE
)

library(tidyverse)
library(readxl)
source("cv_printing_functions.r")

# Read data (from csv)
data_path <- params$data_path
cv <- create_cv_object(data_path)
cv_name <- params$cv_name

# Print sections if TRUE
eval_text <- params$summary
eval_sof  <- params$software
eval_lan  <- params$languages
eval_edu  <- params$education
eval_emp  <- params$employment
eval_tea  <- params$teaching
eval_pub  <- params$publications
eval_pck  <- params$packages
eval_app  <- params$apps

```

```{css, echo=FALSE}

.skill-bar {
  color: white;
  padding: 0.1rem 0.25rem;
  margin-top: 3px;
  position: relative;
  width: 100%;
}

.extra-sidebar {
  top: 0;
  padding-top: 0;
}

.extra-sidebar h1 {
  display: none;
}

.extra-sidebar .level2:first-of-type {
  margin-top: 0;
}

```

Aside
================================================================================

Contact Info {#contact}
--------------------------------------------------------------------------------

```{r contact_info}

cv %>% print_contact_info()

```

```{r software-heading, eval = eval_sof} 

cat("Software {#software}
--------------------------------------------------------------------------------") 

``` 

```{r software, eval = eval_sof}

cv %>% print_skill_bars()

```

```{r languages-heading, eval = eval_lan} 

cat("Languages {#languages}
--------------------------------------------------------------------------------") 

``` 

```{r languages, eval = eval_lan}

cv %>% print_languages()

```

Main
================================================================================

`r cv_name` {#title}
--------------------------------------------------------------------------------

```{r text-block, eval = eval_text}

cv %>% print_text_block("intro")

```

```{r edu-heading, eval = eval_edu} 

cat("Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------") 

``` 

```{r edu, eval = eval_edu}

cv %>% print_section("education", cv_short)

```

```{r emp-heading, eval = eval_emp} 

cat("Employment {data-icon=suitcase}
--------------------------------------------------------------------------------") 

``` 

```{r employment, eval = eval_emp}

cv %>% print_section("employment", cv_short)

```

```{r teaching-heading, eval = eval_tea} 

cat("Training and teaching skills {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------") 

```

```{r teaching, eval = eval_tea}

cv %>% print_section("teaching", cv_short)

```

```{r pub-heading, eval = eval_pub} 

cat("Selected Publications {data-icon=file}
--------------------------------------------------------------------------------") 

```

```{r publications, eval = eval_pub}

cv %>% print_publications(cv_short)

```

Disclaimer {#disclaimer style="width: var(--sidebar-width); padding-left: var(--sidebar-horizontal-padding);"}
--------------------------------------------------------------------------------

This resume was made with [Shiny](https://javierelio.shinyapps.io/cv_app/).

Last updated on `r Sys.Date()`.

Second page sidebar {.aside .extra-sidebar}
================================================================================

```{r packages-heading, eval = eval_pck} 

cat("Software development {#packages}
--------------------------------------------------------------------------------") 

``` 

```{r packages, eval = eval_pck}

cv %>% print_packages()

```

```{r apps-heading, eval = eval_app} 

cat("Apps development {#apps}
--------------------------------------------------------------------------------") 

``` 

```{r apps, eval = eval_app}

cv %>% print_apps()

```


