---
output: 
  vitae::awesomecv

params:
  cv_name: "Javier" 
  cv_surname: "Elio"
  data_path: "cv_data.xlsx"
  summary_long: TRUE
  education_long: TRUE
  employment_long: TRUE
  inv_position_long: TRUE
  membership_long: TRUE
  service_long: TRUE
  project_long: TRUE
  award_long: TRUE
  teaching_long: TRUE
  supervision_long: TRUE
  ext_sensor_long: TRUE
  article_long: TRUE
  book_long: TRUE
  key_1: "Researcher"
  key_2: "Environmental Sciences"
  key_3: "Geoinformatics"
  address: NULL
  phone: +45 9940 2529
  email: "javiereliomedina@gmail.com"
  www: javierelio.netlify.app
  github: javiereliomedina
  linkedin: javiereliomedina
  twitter: elio_javi
     
name: "`r params$cv_name`" 
surname: "`r params$cv_surname`"
date: "`r format(Sys.time(), '%B, %Y')`"
position: "`r params$key_1` | `r params$key_2` | `r params$key_3`"
address: "`r params$address`"
phone: "`r params$phone`"
email: "`r params$email`"
www: "`r params$website`"
github: "`r params$github`"
linkedin: "`r params$linkedin`"
twitter: "`r params$twitter`"

header-includes:
  - \usepackage{colortbl}
  - \usepackage{longtable}
  - \usepackage{float}
  - \arrayrulecolor{white}
  - \definecolor{darktext}{HTML}{414141}
  - \definecolor{blue}{rgb}{0.0, 0.0, 1.0}
  
---

```{r setup, include = FALSE}

knitr::opts_chunk$set(
  results = 'asis', 
  echo = FALSE,
  message = FALSE, 
  warning = FALSE
)

library(tidyverse)
library(readxl)
library(knitr)
library(kableExtra)
library(vitae)

source("cv_long_printing_functions.r")

# Read data (from excel)
data_path <- params$data_path
cv <- create_cv_object(data_path)
cv_name <- params$cv_name
cv_surname <- params$cv_surname

# # Print sections if TRUE
eval_text <- params$summary_long
eval_edu  <- params$education_long 
eval_emp  <- params$employment_long
eval_inv  <- params$inv_position_long
eval_mem  <- params$membership_long
eval_ser  <- params$service_long
eval_pro  <- params$project_long
eval_awa  <- params$award_long
eval_tea  <- params$teaching_long
eval_sup  <- params$supervision_long
eval_ext  <- params$ext_sensor_long
eval_art  <- params$article_long
eval_boo  <- params$book_long

# Short sentence with expertise
research_text <- "My research interests are:"

```

\vspace{0.5cm}
\footnotesize 
\rightline{\textcolor{darktext}{\textit{`r pull(filter(cv$text_blocks, loc == "short_description"), text)`}}}
\normalsize
\vspace{1.5cm}

```{r text-block-1, eval = eval_text}
cat("\\vspace{-1cm}\n# Career Summary\n")

cv %>% print_text_block("intro")
```

```{r text-block-2, eval = eval_text}
cat("My research interests are:")
```

```{r text-block-3, eval = eval_text}
cv %>% print_reserch_intrerest()
cat("\\vspace{1cm}")
```

```{r education, eval = eval_edu}
cat("\\vspace{-1cm}\n# Education\n")

cv %>% print_section("education")

```

```{r experience, eval=eval_emp}
cat("\\vspace{-1cm}\n# Experience\n")

cv %>% print_section("employment")
```

```{r inv_positions, eval = eval_inv}
cat("\\vspace{-1cm}\n# Invited positions\n")

cv %>% print_section("inv_position")
```

```{r memberships, eval=eval_mem}
cat("\\vspace{-1cm}\n# Professional memberships\n")

cv %>% print_section("membership")
```

```{r Services, eval=eval_ser}
cat("\\vspace{-1cm}\n# Professional services\n")

cv %>% print_section("service")
```

```{r funding, eval = eval_pro}
cat("\\vspace{-1cm}\n# Funding projects\n")

cv %>% print_section("project")
```

```{r awards, eval=eval_awa}
cat("\\vspace{-1cm}\n# Honours and awards\n")

cv %>% print_section("award")
```

```{r tra-heading, eval = eval_tea | eval_sup | eval_ext}
cat("\\vspace{-1cm}\n# Training and teaching experience\n\\vspace{0.5cm}")
```

```{r lectures, eval=eval_tea}
cat("\\vspace{-0.5cm}\n## Lectures/Seminars\n")

cv %>% print_section("teaching")
```

```{r supervision, eval = eval_sup}
cat("\\vspace{-0.5cm}\n## Supervision\n")

cv %>% print_section("supervision")

```

```{r ext-sensor, eval=eval_ext}
cat("\\vspace{-0.5cm}\n## External sensor\n")

cv %>% print_section("ext_sensor")
```

```{r pub-heading, eval = eval_art | eval_boo}
cat("\\vspace{-1cm}\n# Publications\n\\vspace{0.5cm}")
```

```{r articles, eval = eval_art}
cat("\\vspace{-0.5cm}\n## Peer reviewed articles\n")

cv %>% print_publications("article", cv_surname)
```

```{r books, eval=eval_boo}
cat("\\vspace{-0.5cm}\n## Books and book chapters\n")

cv %>% print_publications("book", cv_surname)
```
